### ISSUE TITLE
Kan man skicka ett ordersvar hur många gånger som helst?

### ISSUE THREAD

**Issue by stnor** [Sambruk/digitala-produkter-bol#9]
Jag tolkar det som att man kan anropa `replyToUrl` hur många gånger som helst för en `Order` till dess att alla `orderRows` är antingen status `delivered` eller `cancelled`. Är det korrekt uppfattat @LM-andreas @MichaelaVesterlund?

**Comment by LM-andreas** [comment]
Du kan göra flera callbacks för en och samma order. Det är korrekt.

**Comment by stnor** [comment]
Tack. Det kanske borde dokumenteras, så jag lämnar denna issue öppen.

**Comment by stnor** [comment]
Är det OK att skicka tillbaka en annan produkt för en `orderRowId`, än det som kommer vid anropet. Det finns en del use-cases för det för oss.

**Comment by MichaelaVesterlund** [comment]
Hej! I dagsläget hos GR kan man inte göra det, men det ligger i vår backlog att undersöka den funkationaliteten. Vilket är use-caset för quantity? Är det om de ångrar antalet, t.ex. de vill köpa mer eller mindre?

**Comment by stnor** [comment]
Det kan vara allt möjligt. Till exempel att dom beställt fel antal eller fel produkt, och så kontaktar vi dem för att vi tycker det ser konstigt ut och reder ut det.

**Comment by MichaelaVesterlund** [comment]
Kvantitet är bara för verifikation. Det som skulle kunna hända är t.ex. att ni i 1a anropet svarar med beingProcessed, för att senare svara med backordered och sen slutligen delivered eller canceled. Det är därför man kan svara flera gånger.

**Comment by LM-andreas** [comment]
Att svara med annat ISBN är ett konkret behov som kommit upp i och med att flera förlag lanserat digitala paket. Själva paketet är bara en container för de produkter som faktiskt ska kunna administreras. Därför behöver man kunna ta emot andra ISBN än de som man faktiskt beställts.

**Comment by stnor** [comment]
Detta behöver dokumenteras om det nu är koncensus, eller hur nu besluten
går till.

Jag skickade ett mail till GR med lite andra frågor. Du kanske kan kolla på
dessa och svara på det?

**Comment by stnor** [comment]
Det rimliga är väl att man tar bort allt utan id och status om man inte får
ändra dem?

**Comment by MichaelaVesterlund** [comment]
@stnor vilken adress har du skickat till?

**Comment by stnor** [comment]
Det var en mailväxling med Johan N och Johan B.

**Comment by MichaelaVesterlund** [comment]
Ja om det är ett paket, vi har inte implementerat stödet för paket ännu.

**Comment by stnor** [comment]
@MichaelaVesterlund  Vad är definitionen av ett "paket" och hur vet ni att min produkt är ett paket eller ej? Vem bestämmer det? I dokumentationen står det att leverantören bestämmer sina egna articleIds och inget om varken ISBN eller "paket". De som är digitala natives som vi, har inga ISBN för produkterna.

**Comment by MichaelaVesterlund** [comment]
Ett paket är en artikel som innehåller flera artiklar, t.ex. artikel "Matematik A Paket" med artikelnummer "matte-p" innehåller 1 lärarhandledning (artikelnummer "lärar-web") och 10 elevlicenser(artikenummer "elev-web"). Leverantören bestämmer om sin artikel är ett paket, information om detta ges till oss. Leverantören behöver ge oss unika artikelnummer som ni bestämmer själva. Så om vi skickar en beställning till er med matte-p, då kan vi förvänta oss svar med 1 lärar-web och 10 elev-web.

**Comment by stnor** [comment]
Vidare så har våra produkter inte ISBN, utan det är en kod som vi bestämmer.

**Comment by MichaelaVesterlund** [comment]
Vi får förtydliga detta i statuskoderna.
